name: "Archive Issues and Pull Requests"

on:
  schedule:
    - cron: '0 0 * * 0,2,4'
  repository_dispatch:
    types: [archive]
  workflow_dispatch:
<<<<<<< HEAD
    inputs:
      archive_full:
        description: 'Recreate the archive from scratch'
        default: false
        type: boolean
=======
>>>>>>> 11822596029208b4fb7d68637caa4231a8caf686

jobs:
  build:
    name: "Archive Issues and Pull Requests"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

<<<<<<< HEAD
    # Note: No caching for this build!

    - name: "Update Archive"
      uses: martinthomson/i-d-template@v1
      env:
        ARCHIVE_FULL: ${{ inputs.archive_full }}
=======
    - name: "Update Archive"
      uses: martinthomson/i-d-template@v1
>>>>>>> 11822596029208b4fb7d68637caa4231a8caf686
      with:
        make: archive
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      with:
        make: gh-archive
        token: ${{ github.token }}

    - name: "Save Archive"
      uses: actions/upload-artifact@v2
      with:
        path: archive.json
