name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
<<<<<<< HEAD
      uses: actions/checkout@v3
=======
      uses: actions/checkout@v2
>>>>>>> 11822596029208b4fb7d68637caa4231a8caf686

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

<<<<<<< HEAD
    - name: "Setup"
      id: setup
      run: date -u "+::set-output name=date::%FT%T"

    - name: "Caching"
      uses: actions/cache@v3
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-
=======
    - name: "Cache Setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"

    - name: "Cache References"
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.cache-setup.outputs.path }}
          .targets.mk
        key: refcache-${{ steps.date.outputs.date }}
        restore-keys: |
          refcache-${{ steps.date.outputs.date }}
          refcache-
>>>>>>> 11822596029208b4fb7d68637caa4231a8caf686

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload

    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v2
      with:
        path: "draft-*-[0-9][0-9].xml"
